### ISSUE TITLE
MPAS-A fails to build with 4.8 series GCC compilers

### ISSUE THREAD

**Issue by douglasjacobsen** [MPAS-Dev/MPAS#124]
When building the atmosphere core with 4.8 series GCC compilers, an undefined reference is presented in mpas_atmphys_todynamics.F.

Here is the output from the build:
./libdycore.a(mpas_atmphys_todynamics.o): In function '__mpas_atmphys_todynamics_MOD_tend_toedges':
mpas_atmphys_todynamics.F:(.text+0x716): undefined reference to 'mpas_dmpar_exch_halo_field_'
mpas_atmphys_todynamics.F:(.text+0x785): undefined reference to 'mpas_dmpar_exch_halo_field_'

Adding a "use mpas_dmpar" to the top of mpas_atmphys_todynamics.F fixes the issue.
